# Generated by Django 2.2.5 on 2019-09-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('url', models.CharField(max_length=2048)),
                ('parsed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
