# Generated by Django 2.2.5 on 2019-09-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='parsed',
            new_name='created',
        ),
    ]
